<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\building-blocks\TelesEducacao.Core\TelesEducacao.Core.csproj" />
    <ProjectReference Include="..\..\building-blocks\TelesEducacao.MessageBus\TelesEducacao.MessageBus.csproj" />
  </ItemGroup>

</Project>
