# ===== BUILD =====
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# Propriedades MSBuild compartilhadas (TargetFramework, Nullable, TreatWarningsAsErrors...)
COPY Directory.Build.props ./

# Copia apenas os csproj primeiro (cache inteligente)
COPY src/services/TelesEducacao.Auth.API/*.csproj ./services/TelesEducacao.Auth.API/
COPY src/services/TelesEducacao.Auth.Application/*.csproj ./services/TelesEducacao.Auth.Application/
COPY src/services/TelesEducacao.Auth.Data/*.csproj ./services/TelesEducacao.Auth.Data/
COPY src/building-blocks/TelesEducacao.Core/*.csproj ./building-blocks/TelesEducacao.Core/
COPY src/building-blocks/TelesEducacao.MessageBus/*.csproj ./building-blocks/TelesEducacao.MessageBus/
COPY src/building-blocks/TelesEducacao.WebAPI.Core/*.csproj ./building-blocks/TelesEducacao.WebAPI.Core/

# restore só do projeto (não da solution)
RUN dotnet restore ./services/TelesEducacao.Auth.API/TelesEducacao.Auth.API.csproj

# agora copia o resto
COPY src ./

WORKDIR /src/services/TelesEducacao.Auth.API
RUN dotnet publish -c Release -o /app/publish

# ===== RUNTIME =====
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app/publish .

RUN adduser --disabled-password --gecos "" appuser \
    && chown -R appuser:appuser /app
USER appuser

EXPOSE 5101
ENTRYPOINT ["dotnet", "TelesEducacao.Auth.API.dll"]
